language: racket

env:
 - RACKET_VERSION=6.0

before_install:
 - curl -L https://github.com/greghendershott/travis-racket/releases/download/v0.6/install-racket.sh | bash

install:

before_script:

script:
 - /usr/racket/bin/raco test -x .

after_script:
